services:
  api:
    build: ./api
    ports:
      - "5080:5000"
    volumes:
      - ./api/photos:/app/photos
      - ./api/database.sqlite3:/app/database.sqlite3
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  website:
    build: ./website
    ports:
      - "80:80"
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    command: 'mosquitto -c /mosquitto-no-auth.conf'
