services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./photos:/app/photos
      - ./database.sqlite3:/app/database.sqlite3
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
